upgrade:
  name: upgrade-keystone
  image: keystone
  steps:
    - name: backup
      command: /tmp/backup.sh
      files:
        - backup-sh
      volumes:
        - name: backup-dir
          path: /var/ccp/backup/keystone
          type: host
          readOnly: false
    - name: expand
      files:
        - keystone-conf
      command: keystone-manage db_sync --expand
    - name: migrate
      files:
        - keystone-conf
      command: keystone-manage db_sync  --migrate
    - name: roll
      type: rolling-upgrade
    - name: contract
      files:
        - keystone-conf
      command: keystone-manage db_sync --contract
files:
  keystone-conf:
    path: /etc/keystone/keystone.conf
    content: keystone.conf.j2
  backup-sh:
    path: /tmp/backup.sh
    content: backup.sh.j2
    perm: "555"
