upgrade:
  name: upgrade-keystone
  image: keystone
  steps:
    - name: expand
      files:
        - keystone-conf
      command: keystone-manage db_sync --expand
    - name: migrate
      files:
        - keystone-conf
      command: keystone-manage db_sync  --migrate
    - name: roll
      type: rolling-upgrade
    - name: contract
      files:
        - keystone-conf
      command: keystone-manage db_sync --contract
files:
  keystone-conf:
    path: /etc/keystone/keystone.conf
    content: keystone.conf.j2
